add_newline = true

format = """
$os\
$directory\
$container\
$git_branch\
$git_status\
$c\
$cpp\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$raku\
$rlang\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$vlang\
$zig\
$cmd_duration\
$status\
$line_break[❯ ](bold purple)
"""

continuation_prompt = "[∙   ](fg:black)"

[line_break]
disabled = false

[status]
symbol = "✗"
not_found_symbol = "󰍉 Not Found"
not_executable_symbol = " Can't Execute"
sigint_symbol = "󰂭 "
signal_symbol = "󱑽 "
success_symbol = ""
format = "[$symbol](fg:red)"
map_symbol = true
disabled = false

[cmd_duration]
min_time = 1000
format = "[$duration ](fg:yellow)"

[container]
symbol = " 󰏖"
format = "[$symbol ](yellow dimmed)"

[directory]
format = "[ $path](bold fg:white) [$read_only](fg:yellow)"
read_only = " "
truncate_to_repo = true
truncation_length = 4
truncation_symbol = ""

[git_branch]
symbol = ""
style = ""
format = "[ $symbol $branch ](fg:purple)(:$remote_branch)"

[os]
disabled = false
format = "[](fg:blue)[$symbol](bg:blue fg:black)[](fg:blue)"

[os.symbols]
Arch = " "
Alpine = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
NixOS = " "
openSUSE = " "
SUSE = " "
Ubuntu = " "
Macos = " "
Windows = " "

[c]
symbol = ""
format = "[$symbol ](blue)"

[bun]
symbol = ""
format = "[$symbol ](pink)"

[cpp]
symbol = ""
format = "[$symbol ](blue)"

[crystal]
symbol = ""
format = "[$symbol ](white)"

[dart]
symbol = ""
format = "[$symbol ](green)"

[deno]
symbol = ""
format = "[$symbol ](white)"

[dotnet]
symbol = "󰪮"
format = "[$symbol ](green)"

[elixir]
symbol = ""
format = "[$symbol ](purple)"

[elm]
symbol = ""
format = "[$symbol ](yellow)"

[erlang]
symbol = ""
format = "[$symbol ](red)"

[fennel]
symbol = ""
format = "[$symbol ](white)"

[gleam]
symbol = ""
format = "[$symbol ](pink)"

[golang]
symbol = "󰟓"
format = "[$symbol ](blue)"

[gradle]
symbol = ""
format = "[$symbol ](blue)"

[haskell]
symbol = ""
format = "[$symbol ](purple)"

[haxe]
symbol = ""
format = "[$symbol ](yellow)"

[helm]
symbol = ""
format = "[$symbol ](blue)"

[java]
symbol = ""
format = "[$symbol ](red)"

[julia]
symbol = ""
format = "[$symbol ](green)"

[kotlin]
symbol = ""
format = "[$symbol ](pink)"

[lua]
symbol = ""
format = "[$symbol ](blue)"

[nim]
symbol = ""
format = "[$symbol ](yellow)"

[nodejs]
symbol = ""
format = "[$symbol ](green)"

[ocaml]
symbol = ""
format = "[$symbol ](yellow)"

[perl]
symbol = ""
format = "[$symbol ](blue)"

[php]
symbol = ""
format = "[$symbol ](blue)"

[python]
symbol = ""
format = "[$symbol ](yellow)"

[raku]
symbol = ""
format = "[$symbol ](purple)"

[rlang]
symbol = ""
format = "[$symbol ](blue)"

[ruby]
symbol = ""
format = "[$symbol ](red)"

[rust]
symbol = ""
format = "[$symbol ](yellow)"

[scala]
symbol = ""
format = "[$symbol ](red)"

[solidity]
symbol = ""
format = "[$symbol ](white)"

[swift]
symbol = ""
format = "[$symbol ](yellow)"

[vlang]
symbol = ""
format = "[$symbol ](blue)"

[zig]
symbol = ""
format = "[$symbol ](yellow)"
